project_id = "byxymivlhkzpyltiwjfz"

[functions.cast-vote]
verify_jwt = false

[functions.compute-results]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.update-reward-pool]
verify_jwt = false

[functions.ai-feedback]
verify_jwt = false

[functions.publish-results]
verify_jwt = false

[functions.fraud-scan]
verify_jwt = false

[functions.check-subscription-public]
verify_jwt = false
