project_id = "byxymivlhkzpyltiwjfz"

[functions.cast-vote]
verify_jwt = false

[functions.compute-results]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
